### ISSUE TITLE
Problema package feature_extraction

### ISSUE THREAD

**Issue by jgespinosa10** [computervision-xray-testing/pybalu#3]
Hola,
Tengo un problema al tratar de cargar el package feature_extraction. Me dice que no existe el modulo geometric_utils. Tengo pybalu descargado en un environment con los requirements especificados en _requirements.txt_. ¿A qué se debe el problema? ¿Cómo puedo solucionarlo? Entiendo que no debería tener problemas si tengo los requerimientos especificados y me funcionan todo el resto de los packages.

Mis packages son

cython==0.29.6
numpy==1.16.1
scipy==1.1.0
imageio==2.5.0
scikit-image==0.14.2
scikit-learn==0.20.2
tqdm==4.29.1
pybalu==0.2.5

Muchas gracias y espero su respuesta

![image](https://user-images.githubusercontent.com/30691527/55916506-854d6f80-5bba-11e9-9248-014e3319a338.png)

**Comment by cpieringer** [comment]
Hola @jgespinosa10 , pudiste resolver este error?

**Comment by jgespinosa10** [comment]
No, saludos.
