### ISSUE TITLE
Error al importar extracción de caracteristicas

### ISSUE THREAD

**Issue by Jbijit** [computervision-xray-testing/pybalu#5]
Estimado, 

Tratando de utilizar la librería, al realizar lo siguiente:
from   pybalu.feature_extraction import lbp_features, haralick_features, hog_features

Me aparece el siguiente error:
ModuleNotFoundError: No module named 'pybalu.feature_extraction.geometric_utils'

¿Sabes por qué puede estar pasando?

saludos,
Joaquín

**Comment by maxlevill** [comment]
se soluciona instalando C++
